### ISSUE TITLE
API Server Monitoring Visualization

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#102]
On June 7th, we will be promoting our first election -- the California primary election -- to friends and family. I would like to have server monitoring (built in AWS monitoring is fine) for WeVoteServer running so we can watch traffic live, as well as look at traffic history.

**Comment by josephevans** [comment]
Setting up dashboards on AWS for crucial monitoring stats.

**Comment by DaleMcGrew** [comment]
Hi @josephevans, is the API server monitoring in a good place for our June 4th soft launch? Unfortunately I won't be able to meet this weekend to review it with you, but when you get the monitoring to where you think we need it for the soft launch, can you please let me know so I can review? Thank you!

**Comment by DaleMcGrew** [comment]
We will revisit this again in the future. Closing for now.
