### ISSUE TITLE
Fix broken link when suggested voter guide links are added without "http.."

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#1049]
An example suggested voter guide: https://api.wevoteusa.org/vg/create/?voter_guide_possibility_id=1503

(If you sign in with Twitter or Facebook, and then Slack me your We Vote Id, I can give you access to this page.)

"Link to voter guide" just uses the raw link, so we should probably tack on an "http://" for links that don't have "http" at the start of the url.
![Screen Shot 2019-07-23 at 1 34 59 PM](https://user-images.githubusercontent.com/7756031/61745977-8b252600-ad4f-11e9-895d-45da4dbcae30.png)

To navigate the interface:
1. Go to the Voter Guides section
2. Click on "Review Suggested Voter Guides"
3. Click on "Suggest a Voter Guide" and paste in "www.lidbk.com/2019-endorsements" as an example. "Analyze & Save"
4. Then click on the "Edit" button
5. Click on the right-arrow to the right of "Link to voter guide"

The template is here: WeVoteServer/templates/voter_guide/voter_guide_create.html
The view that prepares data for this page is "voter_guide_create_view" in the file WeVoteServer/voter_guide/views_admin.py

**Comment by irascible** [comment]
it's possible that some pages might need an 'https' rather than an 'http'.

**Comment by DaleMcGrew** [comment]
Verified! Thank you for your first check in with We Vote @irascible!
