### ISSUE TITLE
Update c3 servers to new build system & allow TwitterHandle routing

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#105]
Hi Joe, I would love to be able to direct Google Adwords to https://wevote.guide/Defenders (our c3 servers). The changes you made on the c4 servers are working well.

**Comment by josephevans** [comment]
@DaleMcGrew I just updated the c3 server - please take a look and see if everything seems to be working correctly.

**Comment by DaleMcGrew** [comment]
Thank you @josephevans! The twitter handle shortcut works like a charm -- I'll let the Google Adwords team know they can launch their campaign. :)
