### ISSUE TITLE
Suggested Voter Guide: Import Positions Button not updating `more_info_url`

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#1057]
This process that isn’t grabbing the changed `more_info_url` value: https://api.wevoteusa.org/vg/generate_voter_guide_possibility_batch/?voter_guide_possibility_id=1503

![Screen Shot 2019-07-26 at 3 32 12 PM](https://user-images.githubusercontent.com/7756031/61984770-9334ce00-afba-11e9-880f-4a4e719e23ed.png)

**Comment by DaleMcGrew** [comment]
Hello @irascible, I was in this code for another reason, and I think I see why the more_info_url value isn't updating:
WeVoteServer/voter_guide/controllers.py line 252 (`extract_import_position_list_from_voter_guide_possibility`)
We aren't even pulling the more_info_url from the individual VoterGuidePossibilityPosition position, but instead are currently pulling it from the overall VoterGuidePossibility. I will fix this since I have to fix a parallel field, and report back so you can verify.

**Comment by irascible** [comment]
@DaleMcGrew: thanks, and good timing--I was nerving myself up to take another look at it this morning.

**Comment by DaleMcGrew** [comment]
Fixed and verified.
