### ISSUE TITLE
Automate update of GeoIP IP Address Data

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#108]
Create a way to grab the latest version of the Geo IP data that we have bought straight from Maxmind.com.
Background: We buy a database of IP addresses, tied to City/State/ZIP, through a service called MaxMind. When we buy an update, it allows for a month of data updates. Right now we are manually going to the site, downloading a gzip file, placing it on another server, and then telling We Vote to grab and install the latest version of the database. I would like to remove the manual step, and upgrade our installation script to be able to sign into Maxmind.com and always grab the latest version we have paid for.

**Comment by josephevans** [comment]
The admin servers are downloading the latest version automatically. The API servers will grab the latest version from the admin server when code is updated.
