### ISSUE TITLE
Create an Admin tool/script to update We Vote indices

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#110]
It is ok to do the following from server command line. Extra credit if there is also a way to run these functions from admin.wevote.me web page.
- [ ] Modify which fields within each table are indexed (ok to require complete rebuild of all indices)
- [ ] Flush all index data and completely recreate. It would be nice to have a way to do this either for all kinds of data, or one particular kind of data (Candidate data only for example)

**Comment by josephevans** [comment]
This script is on the admin server in /home/ubuntu/populate_data.py. I changed the script so you have to pass all DB and ES credentials as parameters, so there is nothing sensitive in the script itself. Where should this be checked into git?

**Comment by DaleMcGrew** [comment]
Hi @josephevans, thank you for this -- it works great. Maybe copy and paste it into a folder in https://github.com/wevote/WeVoteServer/tree/master/search called "elastic_search"?

**Comment by josephevans** [comment]
Just checked script into search directory.
