### ISSUE TITLE
Send text message via Twilio

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#1118]
Our new "sms" app in WeVoteServer gets all ready to send a text message. This issue is to get actual sending set up with Twilio. (Dale can provide the developer account with credits.)

The sending should happen in this file:
WeVoteServer/sms/models.py
...in the SMSManager function: send_scheduled_sms_via_twilio

Please add variables for Twilio configuration settings to this file (not including the actual credentials):
WeVoteServer/config/environment_variables-template.json

**Comment by utsab** [comment]
Hi @DaleMcGrew, can I take this one on?

**Comment by DaleMcGrew** [comment]
Hi @utsab I'm sorry I didn't close this -- it is already completed.
