### ISSUE TITLE
Elastic Search: A few indexed field names include commas

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#113]
A few of the fields indexed include a comma in the name. These are the ones I’ve found:
organization: organization_website, organization_twitter_handle, twitter_description,

**Comment by josephevans** [comment]
@DaleMcGrew Not sure what you mean "include a comma in the name" -- do you mean the values have commas in them? Is that a problem?

**Comment by DaleMcGrew** [comment]
Hi @josephevans the result shows that the "key" in the response data includes a comma. For example, "state_served_code" is fine, but "organization_website," includes the comma:

------------- RESULT --------------
_score: 1.7513412
_type: organization
_id: 1298
_source: {u'we_vote_id': u'wv02org1282', u'state_served_code': u'NA',
          u'organization_website,': u'http://www.networklobby.org',
          u'organization_twitter_handle,': u'NETWORKLobby',
          u'organization_name': u'NETWORK, A National Catholic Social Justice Lobby',
          u'twitter_description,': u'A #Catholic leader in the global movement for justice & peace. '
                                   u'Organizers of #nunsonthebus. RTs not endorsements.'}
_index: organizations

**Comment by josephevans** [comment]
OK, I found the issue -- I had commas included in the field names. This is now fixed.
