### ISSUE TITLE
Create organizational endorsements importer

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#115]
We Vote is asking organizations to provide their endorsements in a JSON format. The first group to do this is Democracy for America, and they have provided this API endpoint:
http://www2.democracyforamerica.com/api/we_vote_usa_data.json

The specification for this format is here:
https://docs.google.com/document/d/1D90CslIjOPSxyB6XIBPSV07vDlVp5oMNyQPlOrq1Qj4/edit

TODO:
- [x] Add "organization_endorsements_api_url" URL field in the organization table to store the link to this JSON file for each organization. See: WeVoteServer/organization/models.py (Organization model)
- [x] Add a field on this edit page where this URL can be updated: http://localhost:8000/org/1201/edit/ See: WeVoteServer/organization/views_admin.py (organization_edit_view & organization_edit_process_view) and WeVoteServer/templates/organization/organization_edit.html
- [x] Add a link (similar to "Retrieve photos from Wikipedia" and "Scrape org website for Twitter Accounts") that reaches out to the API endpoint, and then stores the candidate and measure position data locally within the import_export_batches system as a new kind of batch set that will create candidates, measures, and the positions that go along with them.

**Comment by udii** [comment]
A few questions:
1) the json includes candidate positions and measure positions, should we import both?
2) what field(s) should be used to look up the candidates/measures?
3) what should be done if a candidate/measure is not found? ignore it? create it? other??

**Comment by DaleMcGrew** [comment]
Hi @udii, here are my thoughts:
1) the json includes candidate positions and measure positions, should we import both?
A: Yes please.

2) what field(s) should be used to look up the candidates/measures?
I would recommend these starting points for example code regarding bringing in:
a.) OFFICES & CANDIDATES: import_export_google_civic/controllers.py (process_contest_office_from_structured_json & process_candidates_from_structured_json)
b.) MEASURES/REFFERENDUM: import_export_google_civic/controllers.py (process_contest_referendum_from_structured_json)

3) what should be done if a candidate/measure is not found? ignore it? create it? other??
We should create new entries if not found. In candidate/models.py you can look for candidate_name or google_civic_candidate_name + state_code. You can also look for an existing record in our database by Twitter handle, or website. In measure/models.py it would be by measure_title + state code.

**Comment by udii** [comment]
Without going into the full details, the update_or_create_\* methods we have in controllers typically require a google_civic_election_id and some we_vote_id to make an update.

The API does not have we_vote_ids, and the google_civic_election_id is optional (and not populated by Democracy for America), so we might not be able to use existing update_or_create_\* in this case.

The alternative is to update based on names, the problem here is that minor spelling differences may create data duplication and data quality issues.

Per previous comment, I'll try to use a combination of name and id to find existing objects, but if not found, I think it would be better not to create new records without first enforcing some data completeness / de-duplication checks and controls.

**Comment by DaleMcGrew** [comment]
Hello @udii, I think that makes sense to not create a candidate, office or measure if it doesn't exist yet. 
3a) Perhaps we could pass in the google_civic_election_id to use with the incoming data (to help with matching). That is "process this file for election X" 

Perhaps we could (as a new Issue) cache "Possible Offices", "Possible Candidates" and "Possible Measures" into an interim table, where the data could be reviewed and augmented before being moved to the master table. This same system could be used for importing the Change Politics data. We could create "Mappings" between "Name from Democracy for America" to "Name within We Vote" that could help with future imports.
Would you like to find a time to discuss by Google Hangout? (I will email you)

**Comment by DaleMcGrew** [comment]
This is ready for a deeper test, but passed all basic tests! Great work @mnneelam.
