### ISSUE TITLE
Twitter banner not retrieving for sfd11 democraticclub (@sfd11dems) | Twitter

### ISSUE THREAD

**Issue by SailingSteve** [wevote/WeVoteServer#1158]
**Yow, first possible clue:**
https://developer.twitter.com/en/apps

Apps owned by this Twitter account are listed below. You cannot create additional apps because your developer account was rejected or suspended. You may still manage your existing apps here, though further action may be taken if any of them violates our policies.

App icon
We Vote Social Voter Guide
App ID
9433049

**Comment by DaleMcGrew** [comment]
Verified, thank you!
