### ISSUE TITLE
Bookmarked items only appear if they are on your local ballot

### ISSUE THREAD

**Issue by zachmonteith** [wevote/WeVoteServer#116]
We would like to have support for users to bookmark races that do not appear on their local ballot: this can be a way for users to express their views to friends who might live in the appropriate district, be better connected with organizations that share their views, and generally increase the WebApp's functionality.

Currently, the only bookmarked items that show up are ones that appear on the local ballot for the address you have put in.

Example:
1) after opening WebApp in browser, navigate to /settings/location and set a location (I used "oakland, ca")
2) once local ballot appears, bookmark a measure or candidate (I bookmarked "Kamala Harris")
3) click the drop down that currently says "All Ballot Items" and select "What I Have Bookmarked"
     (you can also simply navigate to url /bookmarks) and note that the item DOES appear
4) return to /settings/location and enter a new location (I used "ny, ny")
5) once ballot loads, return to "What I Have Bookmarked"
6) note that the item you bookmarked before (in my case, Harris) DOES NOT appear

**Comment by DaleMcGrew** [comment]
We won't be working on this for now.
