### ISSUE TITLE
Run Load test on API server

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#119]
In order to prepare for the 2016 Election, we need to test our API server (while watching monitoring system) to see how it will hold up on election day.

- [x] Identify 3 read-only API calls that we can hit with 10,000 simultaneous requests
- [x] Identify 1-3 write API calls that we can hit with 10,000 simultaneous requests
- [x] Run the tests (using load testing service) while watching monitoring, make optimizations, and repeat

**Comment by udii** [comment]
I've created a simple load test, see [here](https://github.com/udii/WeVoteServer/tree/loadtest/loadtest)

**Comment by DaleMcGrew** [comment]
Thank you @udii and @josephevans!
