### ISSUE TITLE
Integrate the new PDF scanner code into Admin Voter Guide Possibility Scanner

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#1254]
Integrate the new PDF scanner code into the process that starts here:
http://localhost:8001/vg/create/?voter_guide_possibility_id=50&clear_organization_options=0

One possible insertion point is in "voter_guide_create_process_view" in this file ("voter_guide/views_admin.py") around line 899. This is the heart of the code:
candidate/controllers.py with function "find_organization_endorsements_of_candidates_on_one_web_page"

**Comment by DaleMcGrew** [comment]
Hi @SailingSteve, I could have sworn you had gotten this to work, but I think I was mistaken. If there is anything you can do to get PDF scanning working, it would help the political data team.

**Comment by SailingSteve** [comment]
There was the original (all javascript) pdf scanner, which worked for some pages, which I left in the extension.
Then there was the "c" language scanner, that I tested locally and it worked very well.  I was waiting for Joe to install the package on the production servers, before switching the extension over.
Then there is this request, which is to use the "c" language scanner from other places in Python.

**Comment by SailingSteve** [comment]
@DaleMcGrew 
It seems like the install never happened...

Could you open a terminal window to one of the production servers and type

    which pdf2htmlEX

to see if the executable is installed.  If it finds an executable, get a pdf into your dir with

    curl --request GET "https://www.iuoe399.org/media/filer_public/45/77/457700c9-dd70-4cfc-be49-a81cb3fba0a6/2020_lu399_primary_endorsement.pdf" --output endorsement.pdf

finally test pdf2htmlEX with ...

    pdf2htmlEX --dest-dir '.' endorsement.pdf

it should create a file named endorsement.html that should look good in a browser

If installation is a problem... We will use this so infrequently (a few times a day), that I could install it in a free amazon aws instance and call it from the production servers.

**Comment by SailingSteve** [comment]
I'll experiment to see what it would take to run it as an AWS Lambda.

**Comment by SailingSteve** [comment]
https://hub.docker.com/r/cardboardci/pdf2htmlex

**Comment by SailingSteve** [comment]
The docker image https://hub.docker.com/r/cardboardci/pdf2htmlex was installed in AWS in December and it works great!

Here is an example of a transform:
    https://sdcdp.ngpvanhost.com/sites/sdcdp/files/pdf/Endorsements2020G.pdf
to
   https://wevote-temporary.s3.amazonaws.com/Endorsements2020G.html
