### ISSUE TITLE
Investigate: Use Google Sheets to generate JSON for data importing

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#127]
In Issue #122 we need to take data from a Google Spreadsheet and consume it.

I would like to follow a strategy of creating general purpose importers (one for organizations, one for offices, etc.) that can import from JSON files published from Google spreadsheets. This way we can put the data into a specific Google Spreadsheet format, and then point a We Vote admin tool to consume that URL.

For this Issue, please experiment with setting up a Google Sheet with header names that match https://api.wevoteusa.org/apis/v1/docs/measuresSyncOut/
How can we view the Google Sheet as a JSON file?

**Comment by mikelduffy** [comment]
Viewing google spreadsheet data as JSON seems to be fairly straightforward. 
1. Create spreadsheet with appropriate column headers, and data in each row.
2. Make note of the spreadsheet ID from the URL.
3. Change sharing settings to allow anyone with the link to view.
4. Publish the sheet by going to File>Publish.

The JSON URL will be: https://spreadsheets.google.com/feeds/list/**SPREADSHEETID**/od6/public/values?alt=json
You can then access the JSON through an HTTP GET request. An example of the measuresSyncOut data can be found [here](https://spreadsheets.google.com/feeds/list/1pnUz-74fhO751bJFCzcFlh2FV9isQiXyLEhfRWLdxb4/od6/public/values?alt=json).

Each object in the ['feed']['entry'] array contains key value pairs of the column headers with "gsx$" prepended. So for the measuresSyncOut schema, data can be accessed like:

```
import requests, json

def get_data(spreadsheet_URL):
    try:
        response = requests.get(
            url=spreadsheet_URL,
            params={
                "alt": "json",
            },
        )
        print('Response HTTP Status Code: {status_code}'.format(
            status_code=response.status_code))
    except requests.exceptions.RequestException:
        print('HTTP Request failed')
    return response.content

spreadsheetURL = "https://spreadsheets.google.com/feeds/list/1pnUz-74fhO751bJFCzcFlh2FV9isQiXyLEhfRWLdxb4/od6/public/values?alt=json"
data = json.loads(get_data(spreadsheetURL))

#row 1
print data['feed']['entry'][0]
#row 2
print data['feed']['entry'][1]
#row 1, column 'wevoteid'
print data['feed']['entry'][0]['gsx$wevoteid']
#etc.
```

**Comment by DaleMcGrew** [comment]
Verified. Thank you @mikelduffy!
