### ISSUE TITLE
Groom Measures Data: Move into a dedicated Google Sheet

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#128]
We need to have a single Google Sheet with all of the propositions/measures from Change Politics.
https://docs.google.com/spreadsheets/d/1Ec70xE8LFhm55ZTObjVo-HBMT716T0tUjoS2ziBofTo/edit#gid=629087014

Please use this spreadsheet: https://docs.google.com/spreadsheets/d/1v6TXqhCSfY6SGd6bvqnLsCrGccJwSIwJzr1Fb8_ZNio/edit#gid=0
Fields will be "measure_name" and "state_code". Please do not change the exact text they used for all fields -- we will map these names to We Vote Data in another step.

Related to Issue #122 "Create Importer for Change Politics Data"
Related to Issue #127 "Investigate: Use Google Sheets to generate JSON for data importing"

**Comment by mikelduffy** [comment]
Take a look at the spreadsheet and let me know if I understood the issue correctly.

**Comment by udii** [comment]
See https://docs.google.com/spreadsheets/d/1v6TXqhCSfY6SGd6bvqnLsCrGccJwSIwJzr1Fb8_ZNio/edit#gid=0

**Comment by mikelduffy** [comment]
Removed all rows that contained the words district, board, or senate. Results added to sheet "Final".

**Comment by DaleMcGrew** [comment]
Hi @mikelduffy, will you be able to join us at Code for SF tonight to discuss?

**Comment by mikelduffy** [comment]
Yes, I will be there tonight. See everyone then!

**Comment by DaleMcGrew** [comment]
Thank you @mikelduffy for all of this work with OpenRefine! Verified.
