### ISSUE TITLE
Groom Offices Data: Move into a dedicated Google Sheet

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#129]
We need to have a single Google Sheet with all of the offices from Change Politics.
https://docs.google.com/spreadsheets/d/1Ec70xE8LFhm55ZTObjVo-HBMT716T0tUjoS2ziBofTo/edit#gid=629087014

Please use this spreadsheet:
https://docs.google.com/spreadsheets/d/1Gy_SorG2sOvQKxiMXpVqVYc1lmprTs6dsDfjGPLdM8Q/edit#gid=0
Fields will be "office_name", "district" and "state_code".  Please do not change the exact text they used for all fields -- we will map these names to We Vote Data in another step.

Related to Issue #122 "Create Importer for Change Politics Data"
Related to Issue #127 "Investigate: Use Google Sheets to generate JSON for data importing"

**Comment by udii** [comment]
On the attached spreadsheet, on Tab "CO/CA Organization" there is a column C called "Office" but the content seems to be a measure (proposition) and not an office - please advise where to find the list of offices. Thanks.

**Comment by DaleMcGrew** [comment]
Hi Udi, Column C has Offices and Measures intermingled unfortunately. I think we will need to separate them by hand.

**Comment by mikelduffy** [comment]
Take a look at the "Uniques" sheet. It has everything groomed, and the office_name data is consistent across candidates/positions.

**Comment by DaleMcGrew** [comment]
Thank you @mikelduffy for all of this work with OpenRefine! Verified.
