### ISSUE TITLE
Groom Candidates Data: Move into a dedicated Google Sheet

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#130]
We need to have a single Google Sheet with all of the candidates from Change Politics.
https://docs.google.com/spreadsheets/d/1Ec70xE8LFhm55ZTObjVo-HBMT716T0tUjoS2ziBofTo/edit#gid=629087014

Please use this spreadsheet:
https://docs.google.com/spreadsheets/d/12YTjojxJuIt1XUK_pDBgAkDLT-njTXDORgXyKkvUzq4/edit#gid=0
Fields will be "candidate_name", "office_name", "district", "state_code", "website", "twitter_url", "facebook", "political_party" (any others?). Please do not change the exact text they used for all fields -- we will map these names to We Vote Data in another step.

Related to Issue #122 "Create Importer for Change Politics Data"
Related to Issue #127 "Investigate: Use Google Sheets to generate JSON for data importing"

**Comment by mikelduffy** [comment]
I've created two sheets. One with all of the requested data including many duplicated names, and another that has unique records using the candidate_name as a primary key. The problem with the deduped sheet is that some of the duplicate candidate_name entries have different office_name entries (e.g. Aaron Peskin has "San Francisco Board of Supervisors" and "San Francisco County Central Committee"). These can be handled by either keeping both records (easiest, but the majority of entries are duplicates), keeping one entry (which one?), or merging the data separated by commas from all entries into a single record (time consuming and probably messy). Any preference?

**Comment by DaleMcGrew** [comment]
Thank you Mikel, Aaron Peskin is actually running for two positions (he can serve on both simultaneously). It looks like the "Duplicates Sheet" is what we want as it is. I can go through the spreadsheet before importing to double-check the data, but what you have assembled looks good. Thank you!

**Comment by mikelduffy** [comment]
It looks like I made a small mistake while editing some columns where I only took one digit of the district code, but some of them have two digits. A nice thing about openrefine is that all edits are saved as a JSON file that you can edit and reapply to your data to fix small errors like this. I'll fix it tonight or tomorrow and finish uploading the groomed data.

**Comment by mikelduffy** [comment]
Fixed. The uniques sheet has all requested candidate data. The duplicate checker removed all columns where the candidate_name and the office_name were duplicate to take into account edge cases where one person is running for multiple offices.

**Comment by DaleMcGrew** [comment]
Thank you @mikelduffy for all of this work with OpenRefine! Verified.
