### ISSUE TITLE
Groom Positions Data: Move into dedicated Google Sheet(s)

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#132]
We need to have one or more Google Sheets with all of the positions from Change Politics.
https://docs.google.com/spreadsheets/d/1Ec70xE8LFhm55ZTObjVo-HBMT716T0tUjoS2ziBofTo/edit#gid=629087014

Fields will be "organization_name", "candidate_name", "office_name", "measure_name", "stance", "statement", "district" and "state_code" (any others?). Please do not change the exact text they used for all fields -- we will map these names to We Vote Data in another step.

I see two sources in this spreadsheet for positions: 1) CO/CA Organizations, 2) Campaigns, 3) CO/CA Influencers. For "CO/CA Influencers" we may be able to lose the first/last names since we can probably only take in the entries that provide a Twitter handle.

Related to Issue #122 "Create Importer for Change Politics Data"
Related to Issue #127 "Investigate: Use Google Sheets to generate JSON for data importing"

**Comment by mikelduffy** [comment]
Here is a link to a spreadsheet of the groomed positions data: https://docs.google.com/spreadsheets/d/1hvHjsPpTBKt8fLWyUFnmUuhttNquCIZ3g1GReg29uks/pubhtml

Close to 1/3 of the data that has an "organization_name" and an "office_name" or "measure_name" doesn't have data for their "stance". I left that data in the sheet for now, but it can easily be removed if needed.

**Comment by DaleMcGrew** [comment]
Thank you @mikelduffy for all of this work with OpenRefine! Verified.
