### ISSUE TITLE
Add source_code filter for Map Points

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#1365]
We have been doing some updates to our Polling Locations system (now called "Map Points") in the admin tools. Two related tasks:
1)
On this page: http://localhost:8001/pl/
For every unique polling_location.source_code value found in the database (ex/ "PUBLIC_SCHOOLS"), show a checkbox between the filter/search interface and the map points.
![Screen Shot 2020-07-03 at 8 35 24 AM](https://user-images.githubusercontent.com/7756031/86483107-2ec0d980-bd08-11ea-9a79-5cb7f097554d.png)
So if you uncheck the box for PUBLIC_SCHOOLS, those map points would be filtered out.

View file: WeVoteServer/polling_location/views_admin.py
  function: polling_location_list_view

Template file: WeVoteServer/templates/polling_location/polling_location_list.html

2)
On this page:
https://api.wevoteusa.org/pl/0/visualize/?state_code=
...I would love to add a way to filter by "polling_location.source_code". I'm thinking a checkbox for every unique value found in the database in the source_code field, displayed next to the state drop down. So if you uncheck the box for PUBLIC_SCHOOLS, those map points would be filtered out.

View file: WeVoteServer/polling_location/views_admin.py
  function: polling_location_visualize_view

Template file: WeVoteServer/templates/polling_location/polling_location_visualize.html

**Comment by holdenliu** [comment]
Hello Dale, 
     My team(@MarianoMirandaHerrera, @JuanSuria1) and I are working on this issue currently and are having some problems with downloading the map points of every state. So far we have been only able to find 2 unique source_code values, PUBLIC_SCHOOL and POST_OFFICE_LAT_LONG. Our team was wondering if there were any more source_code values that we need to look out for besides the one mentioned.

**Comment by DaleMcGrew** [comment]
@holdenliu @marianomirandaherrera @juansuria1 I apologize for not responding sooner, but we have pulled this issue into our internal team of volunteers. Thank you for taking a look at the issue! https://wevote.applytojob.com/apply/
