### ISSUE TITLE
Elastic search refinement: Search for “Prop 52”

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#140]
When I search for "Prop 52" I do not get any results. When I search for "Proposition 52" I get results. Can we set up Elastic search so that "Prop 52" finds "Proposition 52"?

**Comment by udii** [comment]
See http://dev.paperlesspost.com/setting-up-elasticsearch-synonyms/27 for details

**Comment by udii** [comment]
https://github.com/wevote/WeVoteServer/pull/148

Update to search/populate_data.py, to define a custom analyzer and filter to define the synonym.
Just rerun the script the redefine and populate the indexes.

Tested locally using:
curl 'localhost:9200/measures/_analyze' -d '{ "analyzer" : "measure_synonyms", "text" : "prop 52" }'
and
curl 'localhost:9200/_search?pretty&q=prop%2052'

**Comment by DaleMcGrew** [comment]
Thank you @udii, I was able to pull your changes and run it on the live server. It works!

Will the code that dynamically updates the ContestMeasure search data need to be updated as well?
WeVoteServer/signals/models.py

**Comment by udii** [comment]
No additional updates are needed, once the index is rebuilt with the synonym filter in-place, it will apply to all documents in the index.

**Comment by DaleMcGrew** [comment]
Thank you!
