### ISSUE TITLE
First Apple Sign in: Share email address

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#1408]
1. I tried to sign in with Apple from https://WeVote.US It seemed to succeed.
2. It asked me if I wanted to share my email address. I said yes.
3. I was redirected to this page with this error. 
https://api.wevoteusa.org/apis/v1/appleSignInOauthRedirectDestination
/webapps/wevoteserver/WeVoteServer/apis_v1/views/views_apple.py in sign_in_with_apple_oauth_redirect_view
line 159
first_name = user['name']['firstName'] 

Exception: string indices must be integers

I will share the API page printout via Slack.

**Comment by SailingSteve** [comment]
@DaleMcGrew Does not reproduce.  Can you try again.
That error message seems familiar, I may have fixed it long ago.

**Comment by DaleMcGrew** [comment]
Archiving for later.
