### ISSUE TITLE
Create HTML version of left navigation

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#1502]
We would like to improve the look of our admin tools. Please create a raw HTML version of this, so that these items always hug the left of the screen. I'll see if I can get SVG's for all of these images. Please make the text (Elections, Measures, etc) text and not part of the image. The HTML you create will be woven into our Django Python API server templates and used on most pages. Please include the "We Vote" logo and horizontal bar across the top.

You might also be able to find a Sketch viewer to see this file directly:
https://github.com/wevote/DesignInventory/blob/master/EndorsementGathering/SuggestedVoterGuides-20190415-AhmedG-v2.sketch

<img width="214" alt="Screen Shot 2020-12-11 at 7 56 56 AM" src="https://user-images.githubusercontent.com/7756031/101925671-f9f26180-3b86-11eb-86ef-2b0a1355639c.png">

**Comment by jarodpeachey** [comment]
Hey @DaleMcGrew, sorry for the delay. Where can I find the SVGs for this?

Also, you want a plain HTML file + CSS for this, outside of the WeVote repository?

**Comment by DaleMcGrew** [comment]
Hi @jarodpeachey, no worries! That is correct -- a plain HTML file + CSS. I can then weave the HTML + CSS into the API server. I have attached a ZIP with the SVG files.
[Issue1502_SVGs.zip](https://github.com/wevote/WeVoteServer/files/5853106/Issue1502_SVGs.zip)

**Comment by jarodpeachey** [comment]
OK, here's the HTML + CSS file

[HTML side nav.zip](https://github.com/wevote/WeVoteServer/files/5860979/HTML.side.nav.zip)

**Comment by DaleMcGrew** [comment]
Thank you @jarodpeachey! We will get it integrated.
