### ISSUE TITLE
Integrate HTML Version of Left Navigation into API server

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#1534]
We would like to improve the look of our admin tools. Please integrate the attached HTML into all API server template pages. Do not remove the "Jump to" horizontal links yet:
![Screen Shot 2021-01-24 at 5 37 57 AM](https://user-images.githubusercontent.com/7756031/105632099-745d0500-5e06-11eb-9b69-007fe73ee341.png)

Please note that these navigation items should always hug the left of the screen.

![](https://user-images.githubusercontent.com/7756031/101925671-f9f26180-3b86-11eb-86ef-2b0a1355639c.png)

This was implemented by @jarodpeachey in this issue: 
https://github.com/wevote/WeVoteServer/issues/1502
[HTML.side.nav.zip](https://github.com/wevote/WeVoteServer/files/5862340/HTML.side.nav.zip)

**Comment by SailingSteve** [comment]
All those templates will need to changed.

**Comment by SailingSteve** [comment]
![Screen Shot 2021-01-30 at 7 43 17 PM](https://user-images.githubusercontent.com/6923653/106373966-9e955200-6333-11eb-8cc8-8725c4c629d7.png)

**Comment by SailingSteve** [comment]
![Screen Shot 2021-01-30 at 7 43 17 PM](https://user-images.githubusercontent.com/6923653/106374145-419a9b80-6335-11eb-913d-b057d78871d8.png)

**Comment by DaleMcGrew** [comment]
That is looking great @SailingSteve! Quick comment:

I don't know you have used Django templates, but this pattern would lend itself to adding this navigation to each page. A template like this one:
/WeVoteServer/templates/candidate/candidate_merge_one_field_decision.html
...can be included in another template:
/WeVoteServer/templates/candidate/candidate_merge.html

You can then pass in variables like `with field_name="candidate_name"` to control state information like the at-state for indicating which navigation item (i.e. "Admin Tools") should be highlighted.

**Comment by SailingSteve** [comment]
There were three left navigation buttons that were needed (to replace all the links that were in place), so I added them without icons.

[Errno 2] No such file or directory: '/Users/stevepodell/PycharmProjects/WeVoteServer/apis_v1/static/apis_v1/Home.svg'
[Errno 2] No such file or directory: '/Users/stevepodell/PycharmProjects/WeVoteServer/apis_v1/static/apis_v1/Elected Offices.svg'
[Errno 2] No such file or directory: '/Users/stevepodell/PycharmProjects/WeVoteServer/apis_v1/static/apis_v1/VoterGuidePossibilities.svg'

**Comment by SailingSteve** [comment]
@DaleMcGrew   Re templates:  Yes that was the way I did it.  It replaced the 15ish blocks of code, that mostly were the same (hard to maintain 15 copied blocks of code).  I'll check in the code.

**Comment by DaleMcGrew** [comment]
Looks great!!
