### ISSUE TITLE
Fast Load Data from We Vote Master Servers (2 errors)

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#1537]
I used the "Fast Load Data from We Vote Master Servers" (very cool new feature!) and noticed these errors:

1)
None of the positions came over. (Specifically position_positionentered)
```
Starting on the position_positionentered table, requesting up to 1,000,000 rows
... Intermediate line count from this request of 1M, returned 130218 rows, cumulative is 130218
... Processing rows 0 through 999999 of table position_positionentered data received from master server.
... SQL executed: DELETE (all) FROM position_positionentered
... Skipped rows in position_positionentered: 63026, 66112, 66113, 66114, 95256, 95257,  were skipped since they had pipe characters in the data
FAILED position_positionentered -- invalid input syntax for type bigint: "wv02off13801"
CONTEXT:  COPY position_positionentered, line 31836, column contest_office_id: "wv02off13801"

... Processing and inserting the chunk of 1M from position_positionentered table took 41.806 seconds, cumulative 41.806
... Retrieved 130218 lines from the position_positionentered table (as JSON) in 42.091 seconds)
... Processing and loading table: position_positionentered  took 42.091 seconds
```

2)
Voter Guide Possibilities didn't come over.

**Comment by SailingSteve** [comment]
I spent a couple of hours on record 31836, but without write access to the db, it was not productive, so I just skip it.  It shouldn't matter for developers data.  And "wv02off13801" is not in that record.

**Comment by DaleMcGrew** [comment]
Hi @SailingSteve is there a way to trap the errors with individual records so they won't stop the rest of the process? The problem is that because of this failure, no positions were brought over.

**Comment by SailingSteve** [comment]
I found it.   No need.  Also very difficult, since it is on the sql import from a csv file - it all has to go in without a failure.
