### ISSUE TITLE
Crashing bug "repair_imported_names"

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#1581]
I cleaned up all of the Politician names. I then went to the Candidates page, clicked "Repair Imported Candidate Names" which goes to this page "https://api.wevoteusa.org/c/repair_imported_names/?is_candidate=true" and immediately got this error:

/webapps/wevoteserver/WeVoteServer/candidate/views_admin.py in repair_imported_names_view
1121. short_office_name = person.contest_office_name[0:30] if person.contest_office_name != "N" else ''

**Comment by SailingSteve** [comment]
@dale is this a different issue than the one you sent me by slack?

**Comment by DaleMcGrew** [comment]
Hi @SailingSteve, yes this is different.

**Comment by SailingSteve** [comment]
Does not reproduce, on my local or on the api server.
