### ISSUE TITLE
Google People API Integration 

### ISSUE THREAD

**Issue by SailingSteve** [wevote/WeVoteServer#1588]
https://developers.google.com/people/v1/getting-started
https://github.com/googleapis/google-api-python-client

**Comment by SailingSteve** [comment]
(WeVoteServerPy3.7) stevepodell@Steves-MacBook-Pro-32GB-Oct-2109 WeVoteServerPy3.7 % pip install google-api-python-client
Requirement already satisfied: google-api-python-client in ./lib/python3.7/site-packages (1.7.11)
Requirement already satisfied: httplib2<1dev,>=0.9.2 in ./lib/python3.7/site-packages (from google-api-python-client) (0.19.0)
Requirement already satisfied: google-auth>=1.4.1 in ./lib/python3.7/site-packages (from google-api-python-client) (1.21.1)
Requirement already satisfied: google-auth-httplib2>=0.0.3 in ./lib/python3.7/site-packages (from google-api-python-client) (0.0.3)
Requirement already satisfied: six<2dev,>=1.6.1 in ./lib/python3.7/site-packages (from google-api-python-client) (1.14.0)
Requirement already satisfied: uritemplate<4dev,>=3.0.0 in ./lib/python3.7/site-packages (from google-api-python-client) (3.0.1)
Requirement already satisfied: setuptools>=40.3.0 in ./lib/python3.7/site-packages (from google-auth>=1.4.1->google-api-python-client) (40.6.3)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in ./lib/python3.7/site-packages (from google-auth>=1.4.1->google-api-python-client) (4.0.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in ./lib/python3.7/site-packages (from google-auth>=1.4.1->google-api-python-client) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in ./lib/python3.7/site-packages (from google-auth>=1.4.1->google-api-python-client) (4.7.2)
Requirement already satisfied: pyparsing<3,>=2.4.2 in ./lib/python3.7/site-packages (from httplib2<1dev,>=0.9.2->google-api-python-client) (2.4.7)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in ./lib/python3.7/site-packages (from pyasn1-modules>=0.2.1->google-auth>=1.4.1->google-api-python-client) (0.4.8)
(WeVoteServerPy3.7) stevepodell@Steves-MacBook-Pro-32GB-Oct-2109 WeVoteServerPy3.7 %

**Comment by SailingSteve** [comment]
https://developers.google.com/people/api/rest/v1/otherContacts/list

**Comment by SailingSteve** [comment]
The quickstart code (all JS, no Python): https://developers.google.com/people/quickstart/js#python-3.x

<img width="275" alt="Screen Shot 2021-04-07 at 10 45 48 AM" src="https://user-images.githubusercontent.com/6923653/113911138-76402e80-978e-11eb-9131-14d12f7a7b1b.png">

Works in an "Unverifed testing mode" with no special oAuth code -- the API flow does it for us.

**Comment by DaleMcGrew** [comment]
First pass complete
