### ISSUE TITLE
Is voterEmailAddressSignIn logic still valid?

### ISSUE THREAD

**Issue by upluke** [wevote/WeVoteServer#1601]
I was planning to write a unit test for this endpoint.  However, I noticed in the web application (wevote.us), the default behavior when we add a new email address is to send a **code** (instead of the /sign_in_email/ link).  Since WeVote no longer sends out a link, then the sign_in_email URL will never be triggered, in which case the /voterEmailAddressSignIn endpoint will never be triggered either.  Does this mean that the /voterEmailAddressSignIn logic is dead code?  If this is the case, I'm guessing I should not write a unit test for this endpoint.

**Comment by DaleMcGrew** [comment]
Hello @upluke, thank you for reaching out. If you are looking for an API endpoint to write a test for, I would recommend this recent addition: https://api.wevoteusa.org/apis/v1/docs/campaignListRetrieve/

**Comment by upluke** [comment]
Thank you @DaleMcGrew for suggesting a new api endpoint. We tried to investigate how this api endpoint is being used in weVote, we tried to search through the webApp code base for "campaignListRetrieve" but couldn't find any matches. Could you tell us where in WeVote.us this endpoint being used?

**Comment by DaleMcGrew** [comment]
Hello @upluke, it turns out another team just wrote an API test for campaignListRetrieve. Another I would suggest is this:
https://api.wevoteusa.org/apis/v1/docs/campaignRetrieve/

It is used by a new site we are creating: https://campaigns.wevote.us/

The codebase is here: https://github.com/wevote/Campaigns

**Comment by upluke** [comment]
Sounds good! Thank you @DaleMcGrew for the update!
