### ISSUE TITLE
Update search to find "Measure X"

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#165]
We have several local ballots that include single letter names, like "Measure X". When you type that in the search bar, it can find "Measure X1", but not "Measure X".

**Comment by josephevans** [comment]
This appears to be a bug in the javascript code. Do a search for "X" with your browser debugger enabled - and look at the result from the API server. It will include "Measure X" but it is not displayed.

**Comment by DaleMcGrew** [comment]
Thank you @josephevans and @udii for the research,  and thank you Joe for the pull request! You've empowered me to figure out why all of the search results aren't being displayed.

**Comment by DaleMcGrew** [comment]
Fixed.
