### ISSUE TITLE
Voters: Create filter to show members, donors & "Chip in" payments

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#1657]
On the Voters list in the API server: https://api.wevoteusa.org/voter/
...please add a way to see which voters have signed up for membership, donated, or "chipped in"

**Comment by SailingSteve** [comment]
<img width="1374" alt="Screen Shot 2021-09-03 at 9 20 58 AM" src="https://user-images.githubusercontent.com/6923653/132037791-87240fe2-9df3-4716-a3a2-d8cf3657ca40.png">

**Comment by DaleMcGrew** [comment]
Looks great! My only comment is that we will still need "Is Verified Volunteer" checkbox.

**Comment by SailingSteve** [comment]
<img width="1464" alt="Screen Shot 2021-09-03 at 9 47 54 AM" src="https://user-images.githubusercontent.com/6923653/132042076-42a10f03-e11a-4bfa-a857-c18cf59ebdfc.png">

**Comment by SailingSteve** [comment]
<img width="1421" alt="Screen Shot 2021-09-03 at 10 00 59 AM" src="https://user-images.githubusercontent.com/6923653/132042172-7f3ecb8f-d540-44b1-82db-6ed44d4446ec.png">
Whoops deleted that bit of markup.  I restored it, and checked it in.
