### ISSUE TITLE
Campaigns: Show amount chipped in

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#1658]
- [x] On the Campaigns listing page: https://api.wevoteusa.org/campaign/
...please add a way to see how much money has been chipped in for a particular campaign. Clicking the amount should take you to the supporters page with a filter showing how much each person has chipped in. 

- [x] Please add to the "Campaign Supporters" page: https://api.wevoteusa.org/campaign/wv02camp3/supporters
...how much has been chipped in by that supporter to this campaign.

- [ ] We will need people on the We Vote team to purchase ads based on these donations, and a way to keep track of how much spent on each campaign after we have used the funds.

**Comment by SailingSteve** [comment]
TODO:

- [ ] Thank you page with navigation button at bottom after donation
- [ ] Try to get email into stripe payment record if a chip in (is there for subscriptions)
- [x] Campaign title missing in chip in history
- [x] Template divide chip in by 100 before displaying
- [x] On /campaign/wv5qcamp1/supporters show chip in

**Comment by DaleMcGrew** [comment]
Hi @SailingSteve, have you had any luck with these two items?
- Thank you page with navigation button at bottom after donation
- Try to get email into stripe payment record if a chip in (is there for subscriptions)
