### ISSUE TITLE
Ballot Ordering Needs to be Organized

### ISSUE THREAD

**Issue by ColettePhair** [wevote/WeVoteServer#172]
Right now, ballot items on "Your Page" show up based on when you supported/opposed them, and it's the same for when I've entered groups' positions in the API.  They should show up in some type of organized hierarchy similar to the way items show up on the "Ballot" page.  Ideally users should be able to rearrange them to make the issues most important to them show up at the top of their page.  

![screenshot 108](https://cloud.githubusercontent.com/assets/20586344/19613487/bb1e765c-97a1-11e6-9b70-179802fb3139.png)

**Comment by ColettePhair** [comment]
I'm actually noticing that not all voter guides are strictly organized based on when items were entered.  In this example, prop 52 stays in place, so that even when new items are added, they end up _above_ prop 52, not below it.  I've seen this in other guides as well where items seem to organize somewhat randomly- plus for some guides, like SF bay guardian, the order seems to change when I return to the page.

![screenshot 109](https://cloud.githubusercontent.com/assets/20586344/19613614/651291d4-97a2-11e6-9e2d-7da5e60d7777.png)

**Comment by DaleMcGrew** [comment]
For now we are organizing ballot items based on Google Civic's order. Prior to getting the Google Civic ballots, we are relying on alphabetical order.
