### ISSUE TITLE
One error shown when installing 'npm run dev-server'

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#25]
On my local machine, I ran this command in 'WeVoteServer/web_app':

`npm run dev-server`

Most everything ran successfully. This message was shown "webpack: bundle is now VALID". But there was one error reported:

```
ERROR in ./app/containers/ReadmePage.jsx
Module not found: Error: Cannot resolve 'file' or 'directory' ./../../README.md in /Users/dalemcgrew/PythonProjects/WeVoteServer/web_app/app/containers
 @ ./app/containers/ReadmePage.jsx 37:26-54
```

**Comment by pertrai1** [comment]
Same issues resolved in #34
