### ISSUE TITLE
Update BallotItem & BallotReturned code to include state_code

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#264]
Whenever we create a personalized ballot for a voter, we store BallotItem and BallotReturned entries. We want to start storing state_code so we can selectively search for ballot items by state. To start filtering by state_code, we need to make sure that every place in the code that stores a BallotItem entry also stores state_code.
- [x] Update all calls to BallotItemManager.update_or_create_ballot_item_for_polling_location to include state_code
- [x] Update all calls to BallotItemManager.update_or_create_ballot_item_for_voter to include state_code
- [x] Update all calls to BallotItemManager.retrieve_ballot_item_for_voter to include state_code
- [x] Update all calls to BallotItemManager.copy_ballot_items to include state_code
- [x] Update all calls to BallotItemManager.retrieve_possible_duplicate_ballot_items to include state_code
- [x] Note: BallotReturned model uses normalized_state
- [x] Update all calls to BallotReturnedManager.create_ballot_returned_with_normalized_values to include state_code
- [x] Update all calls to BallotReturnedManager.is_ballot_returned_different to include state_code
- [x] Update all calls to BallotReturnedManager.update_ballot_returned_with_normalized_values to use state_code
- [x] Update all calls to BallotReturnedManager.find_closest_ballot_returned to use state_code
- [x] Update VoterBallotSaved to use state_code
- [x] Update VoterBallotSavedManager.retrieve_voter_ballot_saved to use state_code
- [x] Update VoterBallotSavedManager.create_voter_ballot_saved to use state_code
- [x] Update copy_existing_ballot_items_from_stored_ballot to use state_code

**Comment by SailingSteve** [comment]
Done, but not checked in:
BallotItemManager.update_or_create_ballot_item_for_polling_location

**Comment by DaleMcGrew** [comment]
Hi Steve, I'd love to review this with you before closing. :)

**Comment by SailingSteve** [comment]
Closed by accident!

**Comment by SailingSteve** [comment]
Talked to Dale today.   Everywhere that google_civic_election_id is stored, we should also be storing state_code.
So go through the code and pair them up in passed parameters, and storage.
Since most/all state_codes are null in our existing data set on the master servers, make valid state_code values not necessary in searches that don't involve BallotItem and BallotReturned.  (We can add that later if we think we need it.)

**Comment by DaleMcGrew** [comment]
Project completed! Thank you @SailingSteve.
