### ISSUE TITLE
Update "slave" API servers to not run db migrations

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#304]
Hi Joe, I am worried that we will mess up our database if I accidentally run the "172-31-2-123" update before the "172-31-22-242". Could you remove the makemigrations and migrate commands from all API servers that aren't considered the "master"?
ssh ip-172-31-2-123.us-west-2.compute.internal "sudo /root/update_system"

**Comment by josephevans** [comment]
This has been completed. Instructions sent to Dale.
