### ISSUE TITLE
Add elastic search logs to We Vote splunk

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#358]
Hi Joe, it would be awesome if we could get Splunk searching the elastic search server's logs as well.

**Comment by josephevans** [comment]
Now indexing ES logs to splunk. NOTE: they are very very boring, nothing has been written since 2016, around when the server was launched.

**Comment by DaleMcGrew** [comment]
Thank you Joe. May they remain boring. :)  I just want to be able to find errors if search ever runs into any.
