### ISSUE TITLE
Upgrade Live AWS Servers to Python 3.6.1

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#361]
Please upgrade Python on our live API servers (WeVoteServer) to version 3.6.1. (note: version 3.6.0 had some issues).

**Comment by josephevans** [comment]
We are currently using Python 3.4.3. Upgrading to 3.6 is a big task, as Ubuntu does not provide it with packages (only the 3.4 train.)

Is there some functionality that you need from 3.6? The 3.4 series is still getting security updates and is probably the most stable at this point.

**Comment by DaleMcGrew** [comment]
I'm looping in @SailingSteve. I don't think there is anything specifically we need yet in 3.6.1, so there is no rush. We just wanted to get ready in case we find ourselves starting to use features that are in 3.6.1 without realizing they aren't backwards compatible. (Most developers are working with 3.6.1 locally.) Do you think you could do the upgrade at some point in the next 30-45 days?

**Comment by SailingSteve** [comment]
There are a fair number of useful improvements in 3.5 and 3.6, and developers (like me) who learn new languages by googling for code snippets may unknowingly code in Python features that run on their local, and would then not run on down-rev app servers.

**Comment by josephevans** [comment]
I'd actually like to get our backend instances to start using Ubuntu 16.04 LTS (instead of 14.04 which we currently use.) I think it will be easier to upgrade to Python 3.6 once this is done.

**Comment by DaleMcGrew** [comment]
That sounds like a good plan. Thank you Joe!

**Comment by josephevans** [comment]
Updated API instances to use Ubuntu 16.04 and install python 3.6.2.

All instances have been changed to Ubuntu 16.04 now.

# python3.6 -V
Python 3.6.2

**Comment by DaleMcGrew** [comment]
Awesome, thank you @josephevans! (cc: @SailingSteve @mshmsh5000 )

**Comment by mshmsh5000** [comment]
🎉
