### ISSUE TITLE
Set up master/slave database structure on AWS and in Django

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#392]
I'd love to set up a master/slave database setup, and get your help specifying within Django/WeVoteServer whether to hit a read/write or read-only database instance with each query. Once I have an example pattern, I can start migrating read-only API calls to use a slave db.
https://docs.djangoproject.com/en/1.11/topics/db/multi-db/
We might want to think about migrating our master read/write WeVoteServer database to the middle of the US, and then have read instances in the middle of the country and on both coasts.

**Comment by mshmsh5000** [comment]
Setting up the read-only replicant in RDS is generally a [one-click affair](https://cl.ly/173h050t0N3m), so we could go ahead and do that if you want to get into the DB routing in Django.

**Comment by mshmsh5000** [comment]
@josephevans set up a read replica already.

**Comment by mshmsh5000** [comment]
@DaleMcGrew I've added the read-only info to the Google Doc and mentioned you there.

**Comment by DaleMcGrew** [comment]
Thank you Matt! I will open another issue to get help setting up a read only database connection in Django.
