### ISSUE TITLE
Add "Search" box to offices admin page

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#419]
https://api.wevoteusa.org/off/?google_civic_election_id=4389

**Comment by mshmsh5000** [comment]
This is closed by #438, correct?

**Comment by DaleMcGrew** [comment]
Hi @mshmsh5000 it will be fixed by #438 but it needs to be verified first.

**Comment by DaleMcGrew** [comment]
Verified. Thank you @bharathdn!
