### ISSUE TITLE
How do we use a read-only database in Django?

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#427]
We have a replicating AWS database in our server network. I would like to start using that end point for API calls that don't require any write activity. For this issue to be satisfied, please:

- [x] Propose changes to WeVoteServer/config/environment_variables-template.json for the read-only database
- [x] Update election/views_admin.py elections_sync_out_view to use the read-only database

**Comment by SailingSteve** [comment]
What calls electionsSyncOut?  I couldn't find a reference in python or React.   If servers are using this to synchronize datasets, Postgres replication would do it much better.  (Probably orders of magnitude faster).

**Comment by SailingSteve** [comment]
We want two sets of django dbs, and two sets of config for them in environment_variables.  Need to figure out how django discovers it's db, most likely on two different instances.

**Comment by SailingSteve** [comment]
/Applications/Postgres.app/Contents/Versions/9.6/bin/pg_dump -p5433 WeVoteServerDB > backup.sql
Create WeVoteServerDbReadOnly with pgAdmin4
/Applications/Postgres.app/Contents/Versions/9.6/bin/psql -p5433 WeVoteServerDbReadOnly < backup.sql

**Comment by SailingSteve** [comment]
Info on how to test this on two macs on your local network:

https://docs.google.com/document/d/1MJML7aT_QjSGtf_R1P9OpeILexRl5Ma5SZDiLuR5A68/edit?usp=sharing

**Comment by SailingSteve** [comment]
I think this is complete.

**Comment by DaleMcGrew** [comment]
Thank you @SailingSteve I have marked this as VerifyFix until we can test it on the production server.

**Comment by DaleMcGrew** [comment]
This is working, thank you @SailingSteve!
