### ISSUE TITLE
Receive Facebook photo offsets on server, and scale background image appropriately

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#431]
We will need to update our image caching code to crop the banner (or reposition the banner within WebApp?), taking into consideration the offset_x and offset_y that Facebook returns to us.

**Comment by SailingSteve** [comment]
This was called "Capture and pass Facebook photo offsets to WebApp"  am renaming it to "Receive Facebook photo offsets on server and scale background image appropriately"

This turned out to be a 100% server side issue, due to the messiness of doing cropping in React.

**Comment by SailingSteve** [comment]
Done

**Comment by DaleMcGrew** [comment]
Hi @SailingSteve, I just got a chance to do a code review. When I test it locally, I am not seeing my Facebook banner update, even after changing my banner on Facebook. Would you like to look at it together?

**Comment by SailingSteve** [comment]
Works again for me! (LOL)

**Comment by DaleMcGrew** [comment]
Fixed! Great work @SailingSteve.
