### ISSUE TITLE
Create Twitter feed analyzer that can pick up endorsements

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#512]
https://twitter.com/CSGV/status/913795293048602626

![screen shot 2017-10-06 at 1 44 47 pm](https://user-images.githubusercontent.com/7756031/31297987-fc326900-aa9c-11e7-8b52-2ea7d942e80b.png)

**Comment by eayoungs** [comment]
Hey, Dale. I'd be interested in picking up this issue. Maybe we can chat about it at Code for SF?

**Comment by DaleMcGrew** [comment]
Hi @eayoungs, I have a more pressing but very related Twitter-scraping Issue I'd love to run by you. I will try to get it written up by tonight. See you there!

**Comment by DaleMcGrew** [comment]
We are going to hold off trying to take in endorsements from Twitter for now.
