### ISSUE TITLE
contest_office_name value missing from CandidateCampaign object

### ISSUE THREAD

**Issue by edward-ly** [wevote/WeVoteServer#525]
If you retrieve a candidate's information through the CandidateCampaign object (by clicking on "retrieve possible Twitter handles" on the "Edit Candidate" page, for instance), the `contest_office_name` property always contains the value `None`, even though the `contest_office_id` and `contest_office_we_vote_id` contain the proper values.

You can view the object in the debugger by placing a breakpoint in the `retrieve_possible_twitter_handles_view` function in `twitter/views_admin.py` and examining the `candidate_campaign` variable.

**Comment by DaleMcGrew** [comment]
Fixed
