### ISSUE TITLE
Charlotte Button not functional

### ISSUE THREAD

**Issue by NeiloDull** [wevote/WeVoteServer#557]
When viewing the 'North Carolina November Municipal General' election, clicking the 'Charlotte' location button has no effect but leaves open the ballot items of whatever was previously loaded.
<img width="1062" alt="screen shot 2017-10-30 at 21 44 45" src="https://user-images.githubusercontent.com/32550677/32194825-c7b8a310-bdbb-11e7-80e5-2e0bc47b2acc.png">

https://wevote.us/ballot

**Comment by DaleMcGrew** [comment]
Fixed! The ballot_location_shortcut was accidentally attached to a voter's ballot as opposed to a polling_location ballot.
