### ISSUE TITLE
Build responsive page: mobile navigation vs. desktop navigation

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#56]
Create a first version of a page with navigation that switches between a mobile device view and a tablet/desktop view. The page itself can be dummy content. Mobile header/footer navigation should match:
https://invis.io/V33KV2GBR
Tablet/Desktop navigation should match:
https://docs.google.com/drawings/d/1ffon_khede7Y5h65nnQpiAMG3E0PXONAXwEJwzSF_e8/edit

**Comment by pertrai1** [comment]
@DaleMcGrew Are these the "main entry points" of the application?

**Comment by DaleMcGrew** [comment]
There are many pages that might be the first page a new voter visits. It would be good if we could run some initial code from a variety of pages if it is the first visit by a browser. Lets discuss!

**Comment by nf071590** [comment]
Hey guys, I'm wondering how we can allow cross-origin headers so that I can
call another server (django) with data on port 8000. When I try to make the
request now I get an error. If you guys don't know I'll keep trying to look
into it.

**Comment by DaleMcGrew** [comment]
I'm sorry Nick I don't know. -Dale
