### ISSUE TITLE
Create method of getting city, state

### ISSUE THREAD

**Issue by pertrai1** [wevote/WeVoteServer#58]
Using GeoLocation we will try to get the city and state of the user and use a placeholder of the input box. If the city and state is wrong, the user can update the city and state.

**Comment by DaleMcGrew** [comment]
There has been some work done on this by Aaron Borden. Please reach out to Dale before working on this.

**Comment by raphaelmerx** [comment]
Work started on this. See the `voterLocationRetrieveFromIP` API

**Comment by DaleMcGrew** [comment]
Works well! Thank you Raphael.
