### ISSUE TITLE
Knock the score of any Google search user at this URL https://uk.linkedin.com down to zero

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#591]
Any person we find at https://uk.linkedin.com won't be an American politician, so we can knock these entries down to a score of zero. Actually any URL that starts with any of these URLs could be zero:
https://www.linkedin.com/pub/dir
https://www.facebook.com/events
https://twitter.com/laufer4council/status/867543532504043520 <-- if it includes "/status/"
https://nz.linkedin.com

**Comment by utsab** [comment]
@DaleMcGrew Could I work on this issue?

**Comment by DaleMcGrew** [comment]
Hi @utsab, yes that would be great! Thank you. I think this would be a good issue to discuss via screenshare though before you get started. Could we connect on Slack to find a time to review this?

**Comment by iansw246** [comment]
I am working this

**Comment by iansw246** [comment]
What would be the best way to store and reference the list of URL patterns?
For the custom Google search engine, what should the configuration be?
