### ISSUE TITLE
Manually bring over Organization-to-Issue links from Vote Smart

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#623]
Vote Smart provides a list of organizations based on issue. We need to use summary lists like this one: https://votesmart.org/interest-groups/NA/13#.Wk_DTVQ-dhE

...to find the groups that are categorized by Vote Smart:
https://votesmart.org/interest-group/935/common-cause#.Wk_Dw1Q-dhE

And then translate their categories into our (similar but slightly different) categorization system:
https://docs.google.com/spreadsheets/d/1Eb9W8kK1wiBfl1jrThjkpizcTHEBjd5F1qIO7LJx_Wk/edit#gid=0
(We should record which categories we've completed in the "All Groups Updated?" tab.) 

...and then add these categories to our database:
https://api.wevoteusa.org/org/1231/edit/?google_civic_election_id=0

As we finish each group, please make record of the group on this tab:
https://docs.google.com/spreadsheets/d/1Eb9W8kK1wiBfl1jrThjkpizcTHEBjd5F1qIO7LJx_Wk/edit#gid=1647701371

**Comment by robla** [comment]
@molliekat and I did a handful of groups over the weekend. Feel free to ping me on Slack about it

**Comment by DaleMcGrew** [comment]
I am going to close this issue for now while we rework our Issues. Thank you @robla and @molliekat for your work so far on categorizing issues!
