### ISSUE TITLE
npm install dependency issues

### ISSUE THREAD

**Issue by pertrai1** [wevote/WeVoteServer#64]
@DaleMcGrew @nf071590 Have you received this error:

```
npm ERR! peerinvalid The package react@0.14.3 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-async@2.1.0 wants react@>=0.12.0 <0.14.0
npm ERR! peerinvalid Peer react-bootstrap@0.25.2 wants react@>=0.13
npm ERR! peerinvalid Peer react-breadcrumbs@1.1.1 wants react@>=0.12.2 <0.15.0
npm ERR! peerinvalid Peer react-portal@0.7.0 wants react@^0.13.x
npm ERR! peerinvalid Peer react-router@0.13.5 wants react@0.13.x||0.14.x
npm ERR! peerinvalid Peer react-router-component@0.25.4 wants react@>=0.12.0 <0.14.0
npm ERR! peerinvalid Peer reflux@0.2.12 wants react@>=0.12.2 <0.14.0
```
When I then build and start I get this error:

```
ERROR in ./~/react-bootstrap/lib/utils/deprecationWarning.js
Module not found: Error: Cannot resolve module 'react/lib/warning' 
in /media/psf/Repos/WeVoteServer/web_app/node_modules/react-bootstrap/lib/utils
 @ ./~/react-bootstrap/lib/utils/deprecationWarning.js 11:23-51

ERROR in ./~/react-bootstrap/lib/utils/CustomPropTypes.js
Module not found: Error: Cannot resolve module 'react/lib/warning' 
in /media/psf/Repos/WeVoteServer/web_app/node_modules/react-bootstrap/lib/utils
 @ ./~/react-bootstrap/lib/utils/CustomPropTypes.js 13:23-51

ERROR in ./~/react-bootstrap/lib/OverlayTrigger.js
Module not found: Error: Cannot resolve module 'react/lib/warning' 
in /media/psf/Repos/WeVoteServer/web_app/node_modules/react-bootstrap/lib
 @ ./~/react-bootstrap/lib/OverlayTrigger.js 32:23-51
```
I can't start the app locally to do any work. Let me know if you have had this issue and how you resolved it. If you have not received it, let me know if you have any ideas on how to fix.

Thanks guys.

**Comment by nf071590** [comment]
Yeah I got all of that. I fixed it manually so I could work but it will
need to be fixed.

**Comment by pertrai1** [comment]
@nf071590 How did you fix it manually? I want to do that so I can work too. Thanks.

**Comment by DaleMcGrew** [comment]
I have not seen this error. -Dale

On Thursday, November 26, 2015, Rob Simpson <notifications@github.com>
wrote:

> @DaleMcGrew <https://github.com/DaleMcGrew> @nf071590
> <https://github.com/nf071590> Have you received this error:
>
> npm ERR! peerinvalid The package react@0.14.3 does not satisfy its siblings' peerDependencies requirements!
> npm ERR! peerinvalid Peer react-async@2.1.0 wants react@>=0.12.0 <0.14.0
> npm ERR! peerinvalid Peer react-bootstrap@0.25.2 wants react@>=0.13
> npm ERR! peerinvalid Peer react-breadcrumbs@1.1.1 wants react@>=0.12.2 <0.15.0
> npm ERR! peerinvalid Peer react-portal@0.7.0 wants react@^0.13.x
> npm ERR! peerinvalid Peer react-router@0.13.5 wants react@0.13.x||0.14.x
> npm ERR! peerinvalid Peer react-router-component@0.25.4 wants react@>=0.12.0 <0.14.0
> npm ERR! peerinvalid Peer reflux@0.2.12 wants react@>=0.12.2 <0.14.0
>
> When I then build and start I get this error:
>
> ERROR in ./~/react-bootstrap/lib/utils/deprecationWarning.js
> Module not found: Error: Cannot resolve module 'react/lib/warning'
> in /media/psf/Repos/WeVoteServer/web_app/node_modules/react-bootstrap/lib/utils
>  @ ./~/react-bootstrap/lib/utils/deprecationWarning.js 11:23-51
>
> ERROR in ./~/react-bootstrap/lib/utils/CustomPropTypes.js
> Module not found: Error: Cannot resolve module 'react/lib/warning'
> in /media/psf/Repos/WeVoteServer/web_app/node_modules/react-bootstrap/lib/utils
>  @ ./~/react-bootstrap/lib/utils/CustomPropTypes.js 13:23-51
>
> ERROR in ./~/react-bootstrap/lib/OverlayTrigger.js
> Module not found: Error: Cannot resolve module 'react/lib/warning'
> in /media/psf/Repos/WeVoteServer/web_app/node_modules/react-bootstrap/lib
>  @ ./~/react-bootstrap/lib/OverlayTrigger.js 32:23-51
>
> I can't start the app locally to do any work. Let me know if you have had
> this issue and how you resolved it. If you have not received it, let me
> know if you have any ideas on how to fix.
>
> Thanks guys.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wevote/WeVoteServer/issues/64>.
>


-- 

Dale John McGrew
Co-founder, We Vote USA
dale.mcgrew@wevoteusa.org
www.WeVoteUSA.org <http://wevoteusa.org/>
415-516-8777
Facebook: Please Like <http://www.fb.com/WeVoteUSA> We Vote
Twitter: @WeVoteUSA <https://twitter.com/WeVoteUSA>

**Comment by nf071590** [comment]
Where it says cannot resolve 'react... lib/warning.js' or whatever just
change react react to react-router in all three spots.

**Comment by DaleMcGrew** [comment]
I have been trying to install a few items, and I'm hoping they aren't causing these problems. Does anyone mind if we upgrade to "0.14.3"? Here is some error code I just saw while trying to install 'react-tab-view':
---------
dalemcgrew:web_app dalemcgrew$ npm install react-tab-view --save
wevoteusa@0.2.0 /Users/dalemcgrew/PythonProjects/WeVoteServer/web_app
├── UNMET PEER DEPENDENCY react@0.13.3 invalid
├── UNMET PEER DEPENDENCY react-router@0.13.5
└── react-tab-view@1.0.3 

npm WARN EPEERINVALID react-breadcrumbs@1.1.1 requires a peer of react-router@^1.0.0-alpha1 but none was installed.
npm WARN EPEERINVALID react-intl@2.0.0-beta-1 requires a peer of react@^0.14.0 but none was installed.
npm WARN EPEERINVALID react-tab-view@1.0.3 requires a peer of react@^0.14.0 but none was installed.

**Comment by nf071590** [comment]
No I think we should.

**Comment by nf071590** [comment]
Guys,
I would like to re approach some of our build process. I think it needs be
reformed a bit.

I got all of our dependencies reinstalled but the way that our stores are
setup need to be revisited with our build process. I think it will be in
our best interest to have it cleaned up a bit. Let me know what you guys
think and I will get started on this immediately.

NIck

**Comment by DaleMcGrew** [comment]
I totally trust your judgment about the web app build process. Rob, what do
you think?

-Dale

On Friday, November 27, 2015, Nick Fiorini <notifications@github.com> wrote:

> Guys,
> I would like to re approach some of our build process. I think it needs be
> reformed a bit.
>
> I got all of our dependencies reinstalled but the way that our stores are
> setup need to be revisited with our build process. I think it will be in
> our best interest to have it cleaned up a bit. Let me know what you guys
> think and I will get started on this immediately.
>
> NIck
>
> On Thu, Nov 26, 2015 at 9:11 PM, Nicolas Fiorini <nf071590@gmail.com
> <javascript:_e(%7B%7D,'cvml','nf071590@gmail.com');>> wrote:
>
> > No I think we should.
> > On Nov 26, 2015 9:10 PM, "Dale John McGrew" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> >
> >> I have been trying to install a few items, and I'm hoping they aren't
> >> causing these problems. Does anyone mind if we upgrade to "0.14.3"?
> Here is
> >> some error code I just saw while trying to install 'react-tab-view':
> >>
> >> dalemcgrew:web_app dalemcgrew$ npm install react-tab-view --save
> >> wevoteusa@0.2.0 /Users/dalemcgrew/PythonProjects/WeVoteServer/web_app
> >> ├── UNMET PEER DEPENDENCY react@0.13.3 invalid
> >> ├── UNMET PEER DEPENDENCY react-router@0.13.5
> >> └── react-tab-view@1.0.3
> >>
> >> npm WARN EPEERINVALID react-breadcrumbs@1.1.1 requires a peer of
> >> react-router@^1.0.0-alpha1 but none was installed.
> >> npm WARN EPEERINVALID react-intl@2.0.0-beta-1 requires a peer of react@
> ^0.14.0
> >> but none was installed.
> >> npm WARN EPEERINVALID react-tab-view@1.0.3 requires a peer of react@
> ^0.14.0
> >> but none was installed.
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <
> https://github.com/wevote/WeVoteServer/issues/64#issuecomment-160023342>
> >> .
> >>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wevote/WeVoteServer/issues/64#issuecomment-160223040>.
>


-- 

Dale John McGrew
Co-founder, We Vote USA
dale.mcgrew@wevoteusa.org
www.WeVoteUSA.org <http://wevoteusa.org/>
415-516-8777
Facebook: Please Like <http://www.fb.com/WeVoteUSA> We Vote
Twitter: @WeVoteUSA <https://twitter.com/WeVoteUSA>

**Comment by nf071590** [comment]
Okay,  we just have a lot of dependencies that we aren't using and a build
process that does a lot more than what we need. I think there could be a
lot of simplification to the process. While doing this I think I could get
us set up to use the data stores. So I will need to do a little research on
that while I set it up but it shouldn't be an issue.

**Comment by pertrai1** [comment]
@nf071590  That sounds awesome. Look forward to seeing the changes you make. :+1:

**Comment by pertrai1** [comment]
@nf071590 Hey, know you are on vacation. Just checking to see if you will be around today so we can working on slimming down the app? If not, will get with you maybe during the week.

**Comment by pertrai1** [comment]
@nf071590 @DaleMcGrew I was able to get rid of the errors from react-bootstrap which required updating to latest react-bootstrap.

**Comment by nf071590** [comment]
Ah nice. I'm not gonna be available to work during the day today I don't
think. I'm heading down to the pool with my mom and we'll probably be there
most of the day. I may try and get some stuff done later though. Sorry
guys, keep me updated.

**Comment by pertrai1** [comment]
@nf071590 Let me know what time you think and we might be able to do hangout

**Comment by DaleMcGrew** [comment]
The new framework is working great!
