### ISSUE TITLE
App does not work in Firefox

### ISSUE THREAD

**Issue by pertrai1** [wevote/WeVoteServer#65]
@nf071590 @DaleMcGrew Currently the app is not working in Firefox on Linux Mint 17.3. Will have to look into the issue - which I think might be ES2015 related, but not sure of that yet.

**Comment by DaleMcGrew** [comment]
That matches my experience too. It doesn't work on Mac Firefox or Mac Safari either.

**Comment by DaleMcGrew** [comment]
The new Framework works well on Firefox.
