### ISSUE TITLE
Updates to Twitter description not happening on subsequent sign in.

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#757]
It seems like we aren't updating the voter's Twitter description on 2nd+ signins.

**Comment by SailingSteve** [comment]
@DaleMcGrew Does this mean, that if they change their image or display name at twitter, then subsequently when the voter signs into the webapp we don't pick up the changes?

**Comment by DaleMcGrew** [comment]
Hi @SailingSteve, I believe it was that their Twitter description doesn't get updated. So for example on this page: https://twitter.com/wevote
Updates to "We Vote is the place to find..." within Twitter don't get pulled into We Vote's database when you sign in with Twitter into We Vote a second time.
