### ISSUE TITLE
Retrieve Elected Officials from Google's representativeInfoByAddress API

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#768]
Design brief here--step 1 is already complete:
https://docs.google.com/document/d/1qAHm-8dI3UikmJs4qHQYusBaYWMpcKSHd4J4e9Le92E/edit#heading=h.precemq25246

**Comment by SailingSteve** [comment]
Both the Offices and Officials come in at the same time on the same API call, so I add them both at once.

I put a visible note on the Officials page saying that you can load both from the Offices page, and would be happy to put ui on the offices page that calls the same function.  (but please don't just copy the code over, almost identical code is hard to maintain at a high level of quality and reliability).

**Comment by DaleMcGrew** [comment]
Archiving for later.
