### ISSUE TITLE
Very slow voterGuidesToFollowRetrieve API performance causes trouble

### ISSUE THREAD

**Issue by SailingSteve** [wevote/WeVoteServer#797]
We have a very very slow api, voterGuidesToFollowRetrieve, that is paged, and for the California election the 3 pages takes about 45 seconds to complete.  It causes all kinds of delays, lack of UI fluidity (bordering on freezes), and makes the first minute of the app session mediocre on the WebApp and much worse in Cordova.

In addition to not wanting to wait for so long for the data, the server is grinding away for 45 seconds on each new session startup (based on the California election complexity).

**I'm going to start this one off at priority 2 for the project, but it is priority 1 for Cordova.**

<img width="1032" alt="screen shot 2018-06-14 at 9 49 35 am" src="https://user-images.githubusercontent.com/6923653/41426429-72de57fe-6fb8-11e8-8926-1844e2668ba8.png">
<img width="1003" alt="screen shot 2018-06-14 at 9 49 57 am" src="https://user-images.githubusercontent.com/6923653/41426431-76767f36-6fb8-11e8-916d-2a1dcee4b842.png">

**Comment by SailingSteve** [comment]
@DaleMcGrew 
Hi Dale, 
   The previous performance changes on the React side helped a lot, and I could keep going down that path for lower value queries -- all the time trying to get the performance of Cordova up to acceptable.  The highest payoff query to optimize server side, is still voterGuidesToFollowRetrieve, and it is a performance blocker for Cordova.
   I'd like to try adding Redis to the API server. Based on the metrics in this issue, even if we took the query in Python and coded it to be 5x  faster, it would still be very processor and disk intensive.  I looked through the code, there are many places we make python calls that are NOT voter_we_vote_id specific -- those would be great candidates to cache.  That voterGuidesToFollowRetrieve query is paged 3x for California, so we are running parts of the same query 3 times for one dataset update.
  I would add Redis, so that its use is configurable and optional, so that we could optionally use Redis on dev machines, and to not rule out using the Redis version of ElastiCache in case we wanted to share a cache between multiple instances.
  I bet I could get that 45 seconds to down to 0.1 seconds for the second identical query by the same user (we do that!), and maybe in half or a quarter for the first query for the same election, by a second user.  That would mean many fewer aws instances as loads went up.
  What do you think?

Thanks,
Steve
 
https://www.fullstackpython.com/blog/install-redis-use-python-3-ubuntu-1604.html

**Comment by DaleMcGrew** [comment]
Hi @SailingSteve, I’d like to discuss first, perhaps early this next week?

I think the way we work with voter-guides-to-follow needs to be refactored on both the server and in WebApp (not just raw performance improvements). I have been thinking about one way to do this. The good news is that I don’t think we will see situations with as many guides in another election in 2018 as we did for this recent California election, because I don’t think we’re going to pull the ratings from Vote Smart again.

**Comment by DaleMcGrew** [comment]
I made several improvements that should hold us for the next year or two.
