### ISSUE TITLE
Set up basic monitoring of WeVoteServer

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#80]
Perhaps pingdom? Something that lets us know when the API server is down.

**Comment by pertrai1** [comment]
@DaleMcGrew Yes. Setup an account and we will get it setup

**Comment by DaleMcGrew** [comment]
Pingdom account set up and sending notifications to "serveruptime@wevoteusa.org" within 5 minutes of either wevote.me or api.wevoteusa.org going down. Please let dale.mcgrew@wevoteusa.org if you would like to get these notifications.
