### ISSUE TITLE
positionListForBallotItem retrieves duplicate values

### ISSUE THREAD

**Issue by lisamcho** [wevote/WeVoteServer#82]
positionListForBallotItem retrieves duplicate values (i.e. the same organization name with two different we_vote_ids). It looks like we have duplicate data in the API Server.

**Comment by DaleMcGrew** [comment]
Example URL that shows the problem:
https://api.wevoteusa.org/apis/v1/positionListForBallotItem/?ballot_item_id=734&kind_of_ballot_item=CANDIDATE&voter_device_id=WxVLgpBHHUfD8pPO5FE8YhqGdzuZyMVyZqO4qJue2gxstEexqtg0NuKCTBGHEjn6HENYa58QCliKpMHyVtaSe2Og

**Comment by DaleMcGrew** [comment]
Solve two ways:
1) Create script that checks for duplicate positions in db and removes one.
2) Update positionListForBallotItem to only return one value.

**Comment by lisamcho** [comment]
This also applies to positionListForOpinionMaker

**Comment by DaleMcGrew** [comment]
Unable to recreate.
