### ISSUE TITLE
Change one update script to print to the browser while script is running

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#822]
We have many update scripts that timeout after 60 seconds because they haven't provided results by that time. The goal of this issue is to research how we can do partial prints to the screen (with one example script), so the browser-to-load-balancer-to-api-server stays open, and the administrator can see updates as the script runs.

When the process is finished, it should render a django template to a fresh page. (That is, wipe out the status messages that were sent to the browser while the script was running.)

I set up a test view that you can run here: http://localhost:8001/e/test/

The view is called "test_view" here: WeVoteServer/election/views_admin.py

**Comment by SailingSteve** [comment]
[Finally, Real Time apps in Django](https://blog.heroku.com/in_deep_with_django_channels_the_future_of_real_time_apps_in_django) 

Quotation about "Django Chanels" follows:

When Django was created, over ten years ago, the web was a less complicated place. The majority of web pages were static. Database-backed, Model/View/Controller-style web apps were the new spiffy thing. Ajax was barely starting to be used, and only in narrow contexts.

The web circa 2016 is significantly more powerful. The last few years have seen the rise of the so-called “real-time” web: apps with much higher interaction between clients and servers and peer-to-peer. Apps comprised of many services (a.k.a. microservices) are the norm. And, new web technologies allow web apps to go in directions we could only dream of a decade ago. One of these core technologies are WebSockets: a new protocol that provides full-duplex communication — a persistent, open connection between the client and the server, with either able to send data at any time.

In this new world, Django shows its age. At its core, Django is built around the simple concept of requests and responses: the browser makes a request, Django calls a view, which returns a response that’s sent back to the browser.

This doesn’t work with WebSockets! The view is only around for the lifespan of a single request, and there’s no mechanism to hold open a connection or send data down to the client without an associated request.

Thus: Django Channels. Channels, in a nutshell, replaces the “guts” of Django — the request/response cycle — with messages that are sent across channels. Channels allows Django to support WebSockets in a way that’s very similar to traditional HTTP views. Channels also allow for background tasks that run on the same servers as the rest of Django.

**Comment by SailingSteve** [comment]
I have a solution, that uses a different approach.  Django Templates weren't designed with AJAX in mind, they are just simple render and display pages.  So I added some JavaScript to the election_list.html that pings the server every two seconds.  That "ping" is actually a query of an API, that for now just returns dots "....", but could also return progress "123 out of 965 imported."  The importing process would need to use a global variable (probably a hash map keyed to device_id) to allow that status count to be available to a different API call.

This issue did not have an example problem script, but if one of the problem scripts includes "election_list.html", that script should no longer timeout (with this checkin as-is).

**Comment by DaleMcGrew** [comment]
Thank you @SailingSteve!
