### ISSUE TITLE
Retrieve candidate Facebook "page" photo

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#840]
Candidates will list a Facebook page with their public profile. We would like to be able to retrieve this photo and use it for the candidate.

Can we use the Google Custom Search Engine tool we have to retrieve photos from Facebook pages?

See: https://developers.facebook.com/docs/graph-api/reference/page/picture/

**Comment by SailingSteve** [comment]
```<a aria-label="Profile picture" class="_2dgj" href="/24413227922/photos/10155764935092923/" rel="theater"><img class="_4jhq img" height="180" src="https://scontent.fsnc1-1.fna.fbcdn.net/v/t1.0-1/p480x480/19420547_10155764935092923_4741672932915645516_n.jpg?_nc_cat=0&amp;oh=2cac9b689b5117adf09ecae347fbe06b&amp;oe=5BDE0687" width="180" alt=""></a>```

These would be pretty easy to scrape, if we needed to
https://scontent.fsnc1-1.fna.fbcdn.net/v/t1.0-1/p480x480/19420547_10155764935092923_4741672932915645516_n.jpg?_nc_cat=0&oh=2cac9b689b5117adf09ecae347fbe06b&oe=5BDE0687

<a aria-label="Profile picture" class="_2dgj" href="/24413227922/photos/10155764935092923/" rel="theater"><img class="_4jhq img" height="180" src="https://scontent.fsnc1-1.fna.fbcdn.net/v/t1.0-1/p480x480/19420547_10155764935092923_4741672932915645516_n.jpg?_nc_cat=0&amp;oh=2cac9b689b5117adf09ecae347fbe06b&amp;oe=5BDE0687" width="180" alt=""></a>

**Comment by DaleMcGrew** [comment]
The challenge is starting with a Facebook page (Ex/ https://www.facebook.com/KamalaHarris/ ) and then getting back a link to this profile photo) We could also do a CURL call and just look for the URL in the HTML? It would be better if we could do it through the Facebook API thought.

Once we have the image URL, we have a whole system for taking it in, resizing it to various sizes, and caching it on our AWS servers.

**Comment by SailingSteve** [comment]
@DaleMcGrew 
It looks like we would need a page access token to get the picture through the API, in a similar way to the way we get their banner (I made that change last year).  So they would have to be "logged in" to WeVote through facebook.  

I've done lots of scraping in my past, this is an easy one.

What would kick off the scraping?  A admin action, that looked for all of the candidate pages that have facebook URLs but no picture?

**Comment by DaleMcGrew** [comment]
@SailingSteve -- good point. If you are available to join the team hangout now, I can figure it out with you. In the meantime I'll write up a quick design brief:
https://docs.google.com/document/d/1HY-fOssr7AaocBAL1irP8CHp7oj_dGcwzcEY3QI8VJc/edit

**Comment by DaleMcGrew** [comment]
Awesome work @SailingSteve! Verified.
