### ISSUE TITLE
Facebook retrieve should grab phone number and candidate URL

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#864]
When we retrieve a candidate's photo from Facebook with scrape_facebook_photo_url_from_web_page, also try to retrieve the phone number and website.

Ignore this new data if the candidate_phone and candidate_url are already populated in our database.
![screen shot 2018-07-20 at 10 30 46 am](https://user-images.githubusercontent.com/7756031/43016670-6a36e78a-8c08-11e8-9c2e-c56c4792a8b9.png)

**Comment by SailingSteve** [comment]
Facebook made some recent changes that make the scraping of their pages very difficult.  
This is might not be possible.

**Comment by DaleMcGrew** [comment]
Closing this for now.
