### ISSUE TITLE
Wrong candidates/Offices retrieved

### ISSUE THREAD

**Issue by NeiloDull** [wevote/WeVoteServer#873]
1. "Peter McVay" (candidate for New Hampshire House of Representatives Rockingham 14)  appearing in place of "Peter Gagyi" for New Hampshire House of Representatives Merrimack 20. https://api.wevoteusa.org/c/39857/edit/?google_civic_election_id=1000074&state_code=
-Should be https://ballotpedia.org/Peter_Gagyi

2.     "John O'Connor" (Candidate for New Hampshire House of Representatives Rockingham 6) appearing in place of "John J. O'Connor" for     New Hampshire House of Representatives Sullivan 4 https://api.wevoteusa.org/c/wv02cand39771/edit/
-Should be https://ballotpedia.org/John_J._O%27Connor_(New_Hampshire)

**Comment by DaleMcGrew** [comment]
Hello @NeiloDull is this still an issue?

**Comment by DaleMcGrew** [comment]
Could not reproduce.
