### ISSUE TITLE
use X-Header-DeviceId for passing device id instead of GET request query string

### ISSUE THREAD

**Issue by nf071590** [wevote/WeVoteServer#88]
dale, I think this would be a good time to configure the server to use X-Header-DeviceID instead of passing in GET query

new messages
dalemcgrew [10:42 PM] 
Feel free to enter an issue in WeVoteServer and assign it to Joe.

**Comment by DaleMcGrew** [comment]
Hi @nf071590, if you and Joe figure out how to get the WebApp to send "X-Header-DeviceID" (generated from the voter_device_id cookie) with each request, I have set up WeVoteServer to look for that. This is logic:
1) Does "X-Header-DeviceID" exist in the incoming request? If so, use that. Done.
2) If "X-Header-DeviceID" wasn't found, does a voter_device_id GET request exist? If so, use that.

This is the code I'm using `voter_device_id = request.META.get('HTTP_X_HEADER_DEVICEID', '')` -- it is on the live server now.
I will leave this issue open until we have verified it works.

**Comment by josephevans** [comment]
Hey guys, can you provide a little more detail on what this feature is?

Is the client itself (phone client) going to provide the header in the HTTP request? Need help understanding this. Thanks.

**Comment by josephevans** [comment]
I don't think the webapp is going to be able to specific headers to add -- it's the browser that does that and javascript applications can't just generate arbitrary headers. There is the possibility of the proxy generating the header from some other piece of data (such as a cookie or GET request,) is this what you are looking for?

**Comment by DaleMcGrew** [comment]
Hi Joe, here is my understanding. Our Javascript WebApp needs to pass voter_device_id (stored in a cookie) to the WeVoteServer. Currently we are passing it as a GET variable. I believe Nick would prefer to send the value as a header request. I'm not sure what help he needs from you, except perhaps to make sure that the API server is configured to accept custom headers? I'll let him respond with more details.

**Comment by nf071590** [comment]
custom http headers isn't an issue; we should be using Django.

**Comment by josephevans** [comment]
OK, just let me know if any changes need to be done on the load balancer/proxy/server side.

**Comment by josephevans** [comment]
I think this has already been implemented. Can this be closed?

**Comment by DaleMcGrew** [comment]
Yes. Closing.

**Comment by Rishabh31User** [comment]
def post(self, request):
device_id = request.META.get('HTTP_X_HEADER_DEVICE', None)
serializer = DeviceSerializer(data=device_id)
if serializer.is_valid():
serializer.save()
else:
return Response(serializer.errors)

**Comment by Rishabh31User** [comment]
I got the same error non_field_errors": [
"No data provided"
]

I am trying to pass device_id in request header but getting this error . my view is given

**Comment by DaleMcGrew** [comment]
Hello @rishabh31user,  this is a closed issue. We have many open issues on the repo issues page. Please feel free to email me if you have any questions. Dale.McGrew@WeVote.US
