### ISSUE TITLE
voterStarStatusRetrieve with we_vote_id and measure

### ISSUE THREAD

**Issue by lisamcho** [wevote/WeVoteServer#89]
Seems to work fine retrieving with we_vote_id for CANDIDATE and OFFICE.
When I input a MEASURE (wv02meas1), the API server returns:

AttributeError at /apis/v1/voterStarStatusRetrieve/
'ContestMeasureManager' object has no attribute 'fetch_contest_measure_id_from_we_vote_id'

**Comment by DaleMcGrew** [comment]
Fixed!
