### ISSUE TITLE
Increase time until Django times out

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#91]
Would it be possible to increase the Django script timeout duration on the API server?

I am running a scripts that will take 15-30 minutes to complete. I can observe progress through an API call counter for 5-10 minutes, but they aren't completing. (The code is supposed to print results to the log when it completes.) I'd like to figure out a way to keep them running until completion.

**Comment by josephevans** [comment]
I can't find any settings for Django to increase this timeout. I read an article that says it may work if you print some content during the process to stdout (ie to the web client.) Are you currently printing anything while this process is running? 

Alternatively, is there any way to run this as a standalone script or something so we don't have to go through the Load Balancer/proxy configuration?

**Comment by josephevans** [comment]
This should be fixed - I increased the timeout on the ElasticLoadBalancer on Amazon AWS.
