### ISSUE TITLE
duplicates retrieved by voterGuidesToFollow and voterGuidesFollowed

### ISSUE THREAD

**Issue by lisamcho** [wevote/WeVoteServer#93]
There is more than one voter guide returned for each organization. The frontend is currently filtering for uniques on the voter guides (just picking the first one), but it would be better to have the backend decide which voter guide is relevant (we said most recent?) and return only that one.

**Comment by DaleMcGrew** [comment]
Agreed -- thank you for catching this.

**Comment by DaleMcGrew** [comment]
Unable to recreate
