### ISSUE TITLE
set-cookie header

### ISSUE THREAD

**Issue by nf071590** [wevote/WeVoteServer#94]
think about using set-cookie for returning global user data

**Comment by DaleMcGrew** [comment]
Would apply to these API endpoints:
voterRetrieve and voterCreate (not deviceIdGenerate since this call does not create a voter account)

**Comment by nf071590** [comment]
please do not change the name of this issue. this is for using set-cookie in the server response to return global user data.

**Comment by DaleMcGrew** [comment]
Will not fix.
