### ISSUE TITLE
Add "issue_followers_count" to Issues List

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#946]
We expect an "issue_followers_count" value in /WeVoteServer/templates/issue/issue_list.html but it is not being defined in the issue_list_view in /WeVoteServer/issue/views_admin.py

http://localhost:8001/issue/?google_civic_election_id=6000&state_code=

Search for "issue_followers_count" in WeVoteServer.

This "issue_followers_count" value should come from the FollowIssue table in this model: /WeVoteServer/follow/models.py

**Comment by amva13** [comment]
I can take this on.

**Comment by amva13** [comment]
Hey, I want to clarify something - where is the "issue_followers_count" value expected in  /WeVoteServer/templates/issue/issue_list.html ? It never seems to be referenced so my adding a "issue_followers_count" field to template_values is having no effect on the page ?

I see that in the for loop over issues in the html file, we reference the issue.issue_followers_count of the Issue model in /WeVoteServer/issue/models.py and this seems to be what is used as the value for the 'Followers Count' field of the page. I did a quick test and this value is currently 0 for all issues.

Would the approach then be to obtain the correct issue.issue_followers using the mentioned FollowIssue table ? Want to make sure I'm not missing something.

**Comment by amva13** [comment]
@DaleMcGrew ^

**Comment by DaleMcGrew** [comment]
Hi Alejandro @amva13, this is where the value is used in the template (WeVoteServer/templates/issue/issue_list.html):
![screen shot 2018-10-14 at 6 58 41 pm](https://user-images.githubusercontent.com/7756031/46925907-4d86b600-cfe3-11e8-93bb-e47a51b31c5f.png)

You are correct, the task is to make sure the value in models Issue.issue_followers_count is correct, and then get passed to the template. Does that answer your question?

I hope you had a good weekend!

**Comment by amva13** [comment]
Awesome this makes sense thanks Dale ! Hope you enjoyed your weekend as well.

**Comment by amva13** [comment]
will work on this early in the week.

**Comment by amva13** [comment]
Pull request

https://github.com/wevote/WeVoteServer/pull/966
