### ISSUE TITLE
Ballot returning items that are not on ballot? (Calculate actual distance between two locations)

### ISSUE THREAD

**Issue by lisamcho** [wevote/WeVoteServer#95]
According to @sammyds, the election for King County, Washington is a special local election that does not have presidential candidates. The backend voterAddressSave and ballotRetrieve both return a ballot that has presidential candidates.

**Comment by DaleMcGrew** [comment]
voterBallotItemsRetrieve is most likely returning the test election for Washington state, since Google Civic probably doesn't have the live ballot data for this election yet.

**Comment by DaleMcGrew** [comment]
Note: When WebApp issue 169 is completed, we will have text at the top of the ballot telling the voter if it is a test ballot or real ballot: https://github.com/wevote/WebApp/issues/169

**Comment by lisamcho** [comment]
So it is actually returning is_from_test_ballot: false
It returns ballot_caveat: "Ballot displayed is from a nearby address: '231 e 7th st, washington, NC 27889".

You can see the results yourself at https://api.wevoteusa.org/apis/v1/voterAddressSave/?csrfmiddlewaretoken=Q9exThsAH7HUyUeNQwhgg9zejWMTNbnN&voter_device_id=I5l4bR92VMCium8D1nvLWvZnizJtQ8kGj10SuBOvXt7zk2RmlPSx2JTBsxhL0BLiOyz7Xx2LGhjlgXETH6kQCA5f&text_for_map_search=King+County%2C+Washington

**Comment by lisamcho** [comment]
Also might want to add @sammyds to the team roster on Github I'm unable to officially tag him.

**Comment by DaleMcGrew** [comment]
Mind if I change the name of this Issue to "Update find_closest_ballot_returned to use actual distance between two addresses"? This problem will be solved when we look up the lat/long of existing addresses and newly entered addresses (like "King County, Washington"), so we can tell that one is in Washington and the other is in North Carolina. Our current "find_closest_ballot_returned" routine uses a very temporary and simplistic city/state/zip lookup and can't handle situations like this.
PS. I invited "sammyds" just now.

**Comment by raphaelmerx** [comment]
Here's what I can do:
##### From the `text_for_map_search`, find the latitude and longitude. For that, we can use `geopy`:
```python
from geopy.geocoders import Nominatim
geolocator = Nominatim()
# makes an external API call
location = geolocator.geocode("King County, Washington")
latitude, longitude = location.latitude, location.longitude
```

##### query the BallotReturned that's closest

```python
BallotReturned.objects.annotate(distance=(F('latitude') - latitude)**2 + (F('longitude') - longitude)**2
                                ).order_by('-distance')[0]
```

Does that look good to you? If so, I can go ahead and implement it.  
Questions also:
* This implementation would always return a ballot, even if the closest one is far away. Is that fine?
* I don't have any `BallotReturned` in my database. How can I load them?

**Comment by DaleMcGrew** [comment]
This sounds good @raphaelmerx. I will work on getting an export of BallotReturned to you so you have some data to work with. I didn't store latitude or longitudes for those entries, so we probably need to add code to "heal" this data (i.e., retrieve the lat/long and save it if missing)

We will want to filter out Ballot Returned entries that are in different states.

**Comment by DaleMcGrew** [comment]
@DaleMcGrew to Verify this

**Comment by DaleMcGrew** [comment]
Verified. Great work @raphaelmerx!
