### ISSUE TITLE
positionListForBallotItem retrieves blank positions

### ISSUE THREAD

**Issue by lisamcho** [wevote/WeVoteServer#96]
See below request and response....
A position is retrieved, but it has a blank speaker_we_vote_id, no display name, no URL, no nothing...

https://api.wevoteusa.org/apis/v1/positionListForBallotItem/?csrfmiddlewaretoken=Q9exThsAH7HUyUeNQwhgg9zejWMTNbnN&voter_device_id=TumBTY7yu9HSgSPaYzrEnyOEuFxejhSQkfnCPtpPp5olkDADx34pX6DWc3EopHVmhzObDKnUPIF0KK8egF5d4uLu&kind_of_ballot_item=CANDIDATE&ballot_item_id=&ballot_item_we_vote_id=wv02cand431&stance=

**Comment by DaleMcGrew** [comment]
Fixed and live.

**Comment by DaleMcGrew** [comment]
Verified.
