### ISSUE TITLE
Voter address is none, none, none

### ISSUE THREAD

**Issue by lisamcho** [wevote/WeVoteServer#97]
Clearing the cookie and creating a new voter sometimes geocodes the address such that the text_for_map_search (which is what we display on the UI) is "None, none, none" or "None, CA None".

**Comment by DaleMcGrew** [comment]
This is now fixed. I also made sure to return voter_location_found as False when no info is returned.
Location found: https://api.wevoteusa.org/apis/v1/voterLocationRetrieveFromIP/?ip_address=63.70.113.233
Location NOT found: https://api.wevoteusa.org/apis/v1/voterLocationRetrieveFromIP/?ip_address=60.70.113.233

**Comment by lisamcho** [comment]
Verified!
