### ISSUE TITLE
voterAllPositionsRetrieve doesn't recognize unsupport / unoppose actions

### ISSUE THREAD

**Issue by lisamcho** [wevote/WeVoteServer#98]
Nice work on this API, almost done. Here's an issue I found...

Create a new voter ID.
Fetch the voterAllPositionsRetrieve.
It is blank as expected.
Support or oppose two candidates.
It returns two items as expected
Unsupport and unoppose the candidates.
The two items are still returned as voterPositions.

**Comment by DaleMcGrew** [comment]
Hi @lisamcho, thank you! If you stopSupporting or stopOpposing, it sets "is_support" or "is_oppose" (respectively) to false, returning the correct value. We only include positions in the voterAllPositionsRetrieve API endpoint that were previously set as support or oppose. I think we can close this issue.

**Comment by lisamcho** [comment]
@DaleMcGrew I see. You are right, both is_oppose and is_support are false, so it's okay to return the items.
