### ISSUE TITLE
voterAllStarStatusRetrive doesn't return star statuses for all items on ballot

### ISSUE THREAD

**Issue by lisamcho** [wevote/WeVoteServer#99]
I checked it with my voter_device_id, and it only returned statuses for 5 items, even though there are many more on my ballot.

https://api.wevoteusa.org/apis/v1/voterAllStarsStatusRetrieve/?csrfmiddlewaretoken=Q9exThsAH7HUyUeNQwhgg9zejWMTNbnN&voter_device_id=YXcfwW6gv7f2s0zaWuCK6yqaBt8zB0TJabJ0HLkOh4VvSqiVpGgGPkduvs5aTSQpHbRbu7ISLyLqYJAmYSEpUfAI

**Comment by DaleMcGrew** [comment]
Hi Lisa, it is only returning  items that have been starred. Are you saying there are more items that of been starred that are not being returned?

**Comment by lisamcho** [comment]
Hmmm, well I don't see any items that are starred that aren't being
returned. But I do see items that are NOT starred that are being returned
as starred_false, so I guess I just thought that the data was incomplete.
Why would you return starred: false for some items but just not return
anything for other items?

**Comment by DaleMcGrew** [comment]
My thinking was that you could use that to flip off stars that previously had been starred. That is the only reason why there is a "star off" value returned.

**Comment by DaleMcGrew** [comment]
We will leave this as-is (following conversation.)
